---
- hosts: app1
  become: yes

  tasks:
    - name: Disable SELinux
      selinux:
        state: disabled
    
    - name: add groups
      group:
        name: "{{ item }}"
      with_items:
        - sudo
        - tsmgrp
    
    - name: Copy customized sudoers file in place
      copy:
        src: files/sudo
        dest: /etc/sudoers.d/sudo
        validate: /usr/sbin/visudo -csf %s

    - name: Application install
      yum: 
        name: ksh
        state: present

    - name: more complex items to add several users
      user:
        name: "{{ item.name }}"
        uid: "{{ item.uid }}"
        groups: "{{ item.groups }}"
        state: present
      with_items:
        - { name: tsminst1, uid: 1001, groups: "tsmgrp, sudo" }
        - { name: lrsperkins, uid: 1002, groups: sudo }
