---
- hosts: app1
  become: yes

  tasks:
    - name: Disable SELinux
      selinux:
        state: disabled
    
    - name: add groups
      group:
        name: "{{ item }}"
      with_items:
        - sudo
        - tsmgrp
    
    - name: Copy customized sudoers file in place
      copy:
        src: files/sudo
        dest: /etc/sudoers.d/sudo
        validate: /usr/sbin/visudo -csf %s

    - name: Application install
      yum: 
        state: present
        name:
        - ksh
        - lvm2

    - name: more complex items to add several users
      user:
        name: "{{ item.name }}"
        uid: "{{ item.uid }}"
        groups: "{{ item.groups }}"
        state: present
      with_items:
        - { name: tsminst1, uid: 1001, groups: "tsmgrp, sudo" }
        - { name: lrsperkins, uid: 1002, groups: sudo }

  #TODO: set password
  #
    - name: Creataing Spectrum Protect Directories
      file:
        path: "{{ item }}"
        state: directory
        mode: "774"
        owner: tsminst1
        group: tsmgrp
        recurse: yes
      with_items:
        - '/tsm/db'
        - '/tsm/db/db1'
        - '/tsm/db/db2'
        - '/tsm/db/db3'
        - '/tsm/db/db4'
        - '/tsm/log'
        - '/tsm/log/active'
        - '/tsm/log/archive'
        - '/tsm/log/archfail'
        - '/tsm/config'
        - '/tsm/dbbackup'
        - '/tsm/dbbackup/dbbackup1'
