---
- name: formating volumes
  filesystem:
    fstype: xfs
    dev: "{{ item }}"
  with_items:
    - /dev/db_vg/db1_lv
    - /dev/db_vg/db2_lv
    - /dev/db_vg/db3_lv
    - /dev/db_vg/db4_lv
    - /dev/db_vg/config_lv
    - /dev/db_vg/actlog_lv
    - /dev/container_vg/arch_log_lv
    - /dev/container_vg/container1_lv
    - /dev/container_vg/container2_lv
